jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: $(build.artifactstagingdirectory)
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
...
